knpu_oauth2_client:
    clients:
        azure:
            type: azure
            client_id: '%env(OAUTH_AZURE_CLIENT_ID)%'
            redirect_route: connect_azure_check
            redirect_params: {}
            client_secret: '%env(OAUTH_AZURE_CLIENT_SECRET_ID)%'
            tenant: '%env(OUATH_AZURE_TENANT_ID)%'
         

