twig:
    file_name_pattern: '*.twig'
    globals:
        CategoryService: '@App\Service\CategoryService'
#    imefajla: putanja do fajla //pozivam u twig:  {{ imefajla.imefunkcije }} //servis za ucitavanje kategorija
when@test:
    twig:
        strict_variables: true
