controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: '/{_locale}'
    requirements:
        _locale: 'en|sr'
    defaults:
        _locale: 'en'
azure_login:
    path: /connect/azure/check
azure_connect:
    path: /connect/azure
    controller: hwi_oauth.controller.redirectToService
    defaults:
        service: azure

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

